// This file is auto-generated by the deployment script. Do not edit manually.
import deployedContracts from "./deployedContracts.json";

export const CONTRACT_ADDRESSES = {
  tokenA: deployedContracts.tokenA.address,
  tokenB: deployedContracts.tokenB.address,
  dexPool: deployedContracts.dexPool.address
};

export const CONTRACT_ABIS = {
  tokenA: deployedContracts.tokenA.abi,
  tokenB: deployedContracts.tokenB.abi,
  dexPool: deployedContracts.dexPool.abi
};
