const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // 1. Deploy Token A (TKA)
  console.log("Deploying Token A...");
  const Token = await ethers.getContractFactory("Token");
  const tokenA = await Token.deploy("Token A", "TKA");
  await tokenA.waitForDeployment();
  const tokenAAddress = await tokenA.getAddress();
  console.log("Token A deployed to:", tokenAAddress);

  // 2. Deploy Token B (TKB)
  console.log("Deploying Token B...");
  const tokenB = await Token.deploy("Token B", "TKB");
  await tokenB.waitForDeployment();
  const tokenBAddress = await tokenB.getAddress();
  console.log("Token B deployed to:", tokenBAddress);

  // 3. Deploy DexPool (MiniDEX LP)
  console.log("Deploying DexPool...");
  const DexPool = await ethers.getContractFactory("DexPool");
  const dexPool = await DexPool.deploy(tokenAAddress, tokenBAddress);
  await dexPool.waitForDeployment();
  const dexPoolAddress = await dexPool.getAddress();
  console.log("DexPool deployed to:", dexPoolAddress);

  // 4. Seed Pool with initial liquidity (50,000 TKA and 50,000 TKB)
  const liquidityAmountA = ethers.parseEther("50000");
  const liquidityAmountB = ethers.parseEther("50000");

  console.log("Approving DexPool to spend Token A and Token B...");
  await (await tokenA.approve(dexPoolAddress, liquidityAmountA)).wait();
  await (await tokenB.approve(dexPoolAddress, liquidityAmountB)).wait();

  console.log("Adding initial liquidity (50,000 TKA and 50,000 TKB)...");
  await (await dexPool.addLiquidity(liquidityAmountA, liquidityAmountB)).wait();
  console.log("Initial liquidity successfully seeded!");

  // Get current reserves
  const [rA, rB] = await dexPool.getReserves();
  console.log(`Reserves: Token A = ${ethers.formatEther(rA)}, Token B = ${ethers.formatEther(rB)}`);

  // 5. Save contract addresses and ABIs to the frontend directory
  const frontendContractsDir = path.join(__dirname, "../frontend/src/contracts");
  if (!fs.existsSync(frontendContractsDir)) {
    fs.mkdirSync(frontendContractsDir, { recursive: true });
  }

  // Read ABI files generated by compilation
  const tokenArtifactPath = path.join(__dirname, "../artifacts/contracts/Token.sol/Token.json");
  const dexPoolArtifactPath = path.join(__dirname, "../artifacts/contracts/DexPool.sol/DexPool.json");

  const tokenArtifact = JSON.parse(fs.readFileSync(tokenArtifactPath, "utf8"));
  const dexPoolArtifact = JSON.parse(fs.readFileSync(dexPoolArtifactPath, "utf8"));

  const dataToSave = {
    network: {
      chainId: 31337,
      name: "localhost"
    },
    tokenA: {
      address: tokenAAddress,
      abi: tokenArtifact.abi
    },
    tokenB: {
      address: tokenBAddress,
      abi: tokenArtifact.abi
    },
    dexPool: {
      address: dexPoolAddress,
      abi: dexPoolArtifact.abi
    }
  };

  fs.writeFileSync(
    path.join(frontendContractsDir, "deployedContracts.json"),
    JSON.stringify(dataToSave, null, 2)
  );

  // Also write a TypeScript helper file for standard exports
  const helperTs = `// This file is auto-generated by the deployment script. Do not edit manually.
import deployedContracts from "./deployedContracts.json";

export const CONTRACT_ADDRESSES = {
  tokenA: deployedContracts.tokenA.address,
  tokenB: deployedContracts.tokenB.address,
  dexPool: deployedContracts.dexPool.address
};

export const CONTRACT_ABIS = {
  tokenA: deployedContracts.tokenA.abi,
  tokenB: deployedContracts.tokenB.abi,
  dexPool: deployedContracts.dexPool.abi
};
`;

  fs.writeFileSync(path.join(frontendContractsDir, "index.ts"), helperTs);

  console.log("Contract data successfully written to frontend/src/contracts/");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
